2019-07-27 17:37:59,392 -- telegram_bot.log -- main.py -- 124 -- INFO -- /my_id@Bibo_dear_bot
2019-07-27 17:38:00,689 -- telegram_bot.log -- main.py -- 144 -- ERROR -- A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Can\'t find end of the entity starting at byte offset 129"}']
2019-07-27 17:38:07,085 -- telegram_bot.log -- main.py -- 330 -- INFO -- {'type': 'supergroup', 'last_name': None, 'first_name': None, 'username': 'software_tester', 'id': -1001406694070, 'title': '软件测试 test QA', 'all_members_are_administrators': None, 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'sticker_set_name': None, 'can_set_sticker_set': None}
2019-07-27 17:46:55,693 -- telegram_bot.log -- main.py -- 330 -- INFO -- {'type': 'supergroup', 'last_name': None, 'first_name': None, 'username': 'software_tester', 'id': -1001406694070, 'title': '软件测试 test QA', 'all_members_are_administrators': None, 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'sticker_set_name': None, 'can_set_sticker_set': None}
2019-07-27 18:18:33,659 -- telegram_bot.log -- main.py -- 124 -- INFO -- /my_id
2019-07-27 18:18:34,890 -- telegram_bot.log -- main.py -- 144 -- ERROR -- A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Can\'t find end of the entity starting at byte offset 129"}']
2019-07-28 11:55:41,150 -- telegram_bot.log -- main.py -- 100 -- INFO -- [<telebot.types.User object at 0x000002CC56A18BA8>]
2019-07-28 11:55:42,531 -- telegram_bot.log -- main.py -- 122 -- ERROR -- 'list' object has no attribute 'id'
2019-07-28 12:04:53,392 -- telegram_bot.log -- main.py -- 184 -- INFO -- /my_id@Bibo_dear_bot
2019-07-28 12:05:55,348 -- telegram_bot.log -- main.py -- 184 -- INFO -- /my_id@Bibo_dear_bot
2019-07-28 12:14:23,239 -- telegram_bot.log -- main.py -- 103 -- INFO -- [<telebot.types.User object at 0x0000016B03A59518>]
2019-07-28 12:14:23,767 -- telegram_bot.log -- main.py -- 125 -- ERROR -- 'list' object has no attribute 'id'
2019-07-28 12:31:02,831 -- telegram_bot.log -- main.py -- 189 -- INFO -- /my_id@Bibo_dear_bot
2019-07-28 12:37:28,672 -- telegram_bot.log -- main.py -- 73 -- INFO -- /ban
2019-07-28 12:37:45,747 -- telegram_bot.log -- main.py -- 106 -- INFO -- [<telebot.types.User object at 0x000001F373028EB8>]
2019-07-28 12:37:46,289 -- telegram_bot.log -- main.py -- 128 -- ERROR -- 'list' object has no attribute 'id'
2019-07-28 12:42:14,749 -- telegram_bot.log -- main.py -- 73 -- INFO -- /ban
2019-07-28 12:42:25,600 -- telegram_bot.log -- main.py -- 106 -- INFO -- [<telebot.types.User object at 0x0000022CD04169E8>]
2019-07-28 12:42:26,119 -- telegram_bot.log -- main.py -- 128 -- ERROR -- 'list' object has no attribute 'id'
2019-07-28 12:50:10,685 -- telegram_bot.log -- main.py -- 73 -- INFO -- /ban
2019-07-28 12:53:48,343 -- telegram_bot.log -- main.py -- 77 -- INFO -- /ban
2019-07-28 13:01:53,026 -- telegram_bot.log -- main.py -- 58 -- INFO -- /set_black
2019-07-28 13:02:02,117 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:09:19,193 -- telegram_bot.log -- main.py -- 113 -- INFO -- [<telebot.types.User object at 0x0000022C910A9278>]
2019-07-28 13:09:23,662 -- telegram_bot.log -- main.py -- 135 -- ERROR -- 'list' object has no attribute 'id'
2019-07-28 13:10:17,600 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:10:35,390 -- telegram_bot.log -- main.py -- 135 -- ERROR -- 'list' object has no attribute 'id'
2019-07-28 13:11:02,990 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:11:10,346 -- telegram_bot.log -- main.py -- 113 -- INFO -- [<telebot.types.User object at 0x000002D918448AC8>]
2019-07-28 13:11:10,847 -- telegram_bot.log -- main.py -- 135 -- ERROR -- 'list' object has no attribute 'id'
2019-07-28 13:13:23,923 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:13:33,920 -- telegram_bot.log -- main.py -- 134 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:14:36,360 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:14:45,142 -- telegram_bot.log -- main.py -- 134 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:16:06,940 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:16:10,816 -- telegram_bot.log -- main.py -- 85 -- ERROR -- HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot837140525:AAERnzRfG9-Th1kz-3dsYaQ40cMXb5c8crQ/getMe (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=3.5)"))
2019-07-28 13:16:32,126 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:16:40,861 -- telegram_bot.log -- main.py -- 134 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:18:36,604 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:18:38,464 -- telegram_bot.log -- main.py -- 136 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:18:43,095 -- telegram_bot.log -- main.py -- 136 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:19:34,619 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:19:50,369 -- telegram_bot.log -- main.py -- 136 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:22:13,414 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:22:20,263 -- telegram_bot.log -- main.py -- 136 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:26:30,203 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:26:32,088 -- telegram_bot.log -- main.py -- 137 -- ERROR -- 'NoneType' object has no attribute 'id'
2019-07-28 13:26:41,184 -- telegram_bot.log -- main.py -- 137 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:27:12,240 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:27:14,090 -- telegram_bot.log -- main.py -- 137 -- ERROR -- 'NoneType' object has no attribute 'id'
2019-07-28 13:27:20,720 -- telegram_bot.log -- main.py -- 137 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:27:39,259 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:27:41,132 -- telegram_bot.log -- main.py -- 137 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:27:46,989 -- telegram_bot.log -- main.py -- 137 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:29:52,510 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:29:53,992 -- telegram_bot.log -- main.py -- 137 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:30:24,779 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:30:29,099 -- telegram_bot.log -- main.py -- 137 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:31:03,907 -- telegram_bot.log -- main.py -- 137 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:37:03,391 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:37:07,856 -- telegram_bot.log -- main.py -- 136 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:38:26,400 -- telegram_bot.log -- main.py -- 136 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:40:01,915 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:40:06,317 -- telegram_bot.log -- main.py -- 137 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:46:18,219 -- telegram_bot.log -- main.py -- 136 -- ERROR -- 'NoneType' object has no attribute 'first_name'
2019-07-28 13:48:08,005 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:53:52,532 -- telegram_bot.log -- main.py -- 114 -- INFO -- {'id': 690205361, 'is_bot': False, 'first_name': 'voniry', 'username': 'xiaobubu0406', 'last_name': 'chen', 'language_code': 'zh-hans'}
2019-07-28 13:54:17,403 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:54:53,576 -- telegram_bot.log -- main.py -- 119 -- INFO -- {'id': 690205361, 'is_bot': False, 'first_name': 'voniry', 'username': 'xiaobubu0406', 'last_name': 'chen', 'language_code': 'zh-hans'}
2019-07-28 13:56:15,898 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:56:20,517 -- telegram_bot.log -- main.py -- 133 -- INFO -- {'id': 690205361, 'is_bot': False, 'first_name': 'voniry', 'username': 'xiaobubu0406', 'last_name': 'chen', 'language_code': 'zh-hans'}
2019-07-28 13:56:51,990 -- telegram_bot.log -- main.py -- 170 -- INFO -- 讲段子
2019-07-28 13:56:59,988 -- telegram_bot.log -- main.py -- 199 -- INFO -- /my_id@Bibo_dear_bot
2019-07-28 13:57:15,940 -- telegram_bot.log -- main.py -- 78 -- INFO -- /ban
2019-07-28 13:57:28,580 -- telegram_bot.log -- main.py -- 118 -- INFO -- {'id': 690205361, 'is_bot': False, 'first_name': 'voniry', 'username': 'xiaobubu0406', 'last_name': 'chen', 'language_code': 'zh-hans'}
2019-07-28 13:57:41,434 -- telegram_bot.log -- main.py -- 58 -- INFO -- /set_black
2019-07-28 14:00:12,165 -- telegram_bot.log -- main.py -- 265 -- INFO -- {'type': 'private', 'last_name': 'bibo', 'first_name': 'bibo', 'username': 'bibo_dear', 'id': 631099108, 'title': None, 'all_members_are_administrators': None, 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'sticker_set_name': None, 'can_set_sticker_set': None}
2019-07-28 14:00:22,047 -- telegram_bot.log -- main.py -- 227 -- INFO -- {'type': 'private', 'last_name': 'bibo', 'first_name': 'bibo', 'username': 'bibo_dear', 'id': 631099108, 'title': None, 'all_members_are_administrators': None, 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'sticker_set_name': None, 'can_set_sticker_set': None}
2019-07-28 14:01:03,804 -- telegram_bot.log -- main.py -- 227 -- INFO -- {'type': 'supergroup', 'last_name': None, 'first_name': None, 'username': None, 'id': -1001299109373, 'title': 'ddd', 'all_members_are_administrators': None, 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'sticker_set_name': None, 'can_set_sticker_set': None}
2019-07-28 14:02:21,185 -- telegram_bot.log -- main.py -- 227 -- INFO -- {'type': 'private', 'last_name': 'bibo', 'first_name': 'bibo', 'username': 'bibo_dear', 'id': 631099108, 'title': None, 'all_members_are_administrators': None, 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'sticker_set_name': None, 'can_set_sticker_set': None}
2019-07-28 14:02:36,351 -- telegram_bot.log -- main.py -- 227 -- INFO -- {'type': 'supergroup', 'last_name': None, 'first_name': None, 'username': None, 'id': -1001299109373, 'title': 'ddd', 'all_members_are_administrators': None, 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'sticker_set_name': None, 'can_set_sticker_set': None}
